name: Actions Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'develop'

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

