name: Test repository_dispatch

on:
  repository_dispatch:
    types: [test-custom-dispatch-type]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get payload from http post request
        run: |
          echo "${{ github.event.client_payload.foo }}"
          echo "${{ github.event.client_payload.messae }}"
          echo "${{ github.event.client_payload.env }}"

      - name: List Files
        run: |
          pwd
          ls -a
