name: Test Checkout

on:
  schedule:
    - cron: "0/5 * * * *"
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files before checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: List Files after checkout
        run: |
          pwd
          ls -a