name: Test Checkout

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files before checkout
        run: |
          pwd
          ls -a
      - name: Checkout
      - uses: actions/checkout@v3
      - name: List Files after checkout
        run: |
          pwd
          ls -a